# 数据集路径（根据你的实际路径修改）
path: ./dataset  # 数据集根目录
train: images/train  # 训练集图片文件夹
val: images/val      # 验证集图片文件夹
test: images/test    # 测试集图片文件夹（可选）

# 类别信息
nc: 1  # 类别数量（行李箱是1类）
names:
  0: suitcase  # 类别名称
